name: flutter_count_track
description: "Paketleme Takip Sistemi - Üretim fabrikası için paketleme süreçlerini otomatikleştirme ve takip sistemi."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Database
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0

  # Excel Operations
  excel: ^4.0.2

  # PDF Generation
  pdf: ^3.10.8
  printing: ^5.11.1

  # File Operations
  file_picker: ^6.1.1
  open_file: ^3.3.2

  # Audio
  audioplayers: ^5.2.1

  # Charts
  syncfusion_flutter_charts: ^26.2.14

  # Utils
  intl: ^0.19.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  drift_dev: ^2.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/
