name: flutter_count_track
description: "Paketleme Takip Sistemi - Üretim fabrikası için paketleme süreçlerini otomatikleştirme ve takip sistemi."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_riverpod: ^2.4.9

  # Database
  drift: ^2.14.0
  sqlite3: ^2.7.6
  path_provider: ^2.0.0
  path: ^1.8.0

  # Excel Operations
  excel: ^4.0.2

  # PDF Generation
  pdf: ^3.10.8
  printing: ^5.11.1

  # File Operations
  file_picker: ^10.2.0

  # Audio
  audioplayers: ^6.5.0

  # Charts
  syncfusion_flutter_charts: ^29.1.38

  # Utils
  intl: ^0.20.2
  collection: ^1.18.0

  # Supabase Dependencies
  supabase_flutter: ^2.9.1
  connectivity_plus: ^6.1.4
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  drift_dev: ^2.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/
